name: Create Tag and GitHub Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write  # Grant write permissions to GitHub Actions   

jobs:
  create_tag_release:
    if: github.event.pull_request.merged == true
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download zip files
        uses: actions/download-artifact@v4
        with:
          name: zip
          path: zip-files

      - name: Create Git Tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          name: Release ${{ env.NEW_TAG }}
          files: zip-files
          token: ${{ secrets.TARGET_REPO_TOKEN }}
          draft: true
          prerelease: true
